language: node_js

env:
  global:
  - GH_REF=github.com/LoggingRoads/osm-stats-workers.git
  - DEPLOY_BRANCH=loggingroads
  - secure: ""

before_install:
  - chmod +x ./.build_scripts/deploy.sh
  - chmod +x ./.build_scripts/zip.sh

script:
  - "./.build_scripts/zip.sh"

after_success:
  - "./.build_scripts/deploy.sh"
